version: "3"

services:
  demo-valkey-primary:
    image: bitnami/valkey:8.1
    ports:
      - '6389:6379'
    environment:
      - VALKEY_REPLICATION_MODE=primary
      - VALKEY_PASSWORD=root
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'sticky_volume_demo-valkey-primary:/bitnami/valkey/data'

  demo-valkey-secondary:
    image: bitnami/valkey:8.1
    ports:
      - '6388:6379'
    depends_on:
      - demo-valkey-primary
    environment:
      - VALKEY_REPLICATION_MODE=replica
      - VALKEY_PRIMARY_HOST=demo-valkey-primary
      - VALKEY_PRIMARY_PORT_NUMBER=6379
      - VALKEY_PRIMARY_PASSWORD=root
      - VALKEY_PASSWORD=root
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

volumes:
  sticky_volume_demo-valkey-primary:
    driver: local
